### ISSUE TITLE
Add more test cases to reach 95% coverage

### ISSUE THREAD

**Issue by wyf2154** [nyu-devops-squad/shopcarts#101]
The current code coverage is only 94.78%, and we need more test cases to reach the 95% requirement.
A potential problems is to find ways to cover the ```not_found()``` function in ```error_handlers.py``` (line 44). The current version does not cover this function.

**Comment by liqingyang1606** [comment]
We have refactored our code to enable Swagger Docs  (#127 ). The code coverage has reached 96.15%. This is no longer an issue.
