### ISSUE TITLE
Not return error information

### ISSUE THREAD

**Issue by helloyxy** [nyu-devops-squad/shopcarts#114]
**Describe the problem**
In test cases of "sad path", 4xx HTTP status code (400 Bad Request & 404 Not Found) should be returned and displayed at the "Status" part. However, the current implementation doesn't display an error message (both the GUI and the CLI).

**To Reproduce**
1. Go to 'home page'
2. Enter bad data (e.g. a non-existing customer), click on 'Retrieve'
3. See error

**Expected behavior**
return the error message and display it at the "Status" part.

**Comment by liqingyang1606** [comment]
After switching to Flask-RESTX, this issue still exists. No error message shown in the logs or in the "Status" part of the webpage.
