### ISSUE TITLE
set up the tests 

### ISSUE THREAD

**Issue by wyf2154** [nyu-devops-squad/shopcarts#6]
**As a** developer
**I need** to create tests for the moel that represents your resource and develop the code for it
**So that** we can debug the code and make sure the service runs smoothly

**Details & Assumptions:** 
Create a ./test folder to place the test cases.
Start developing by creating the TDD test_xxx.py files that contains your Unit Tests to test your service and model.
Create a models.py file to hold your model definitions of your resource

**Acceptance Criteria:**

```gherkin
Given the test model set up
When developers want to run tests for any feature
Then they can use the test cases in ./test folder and easily run the test
```

**Comment by helloyxy** [comment]
In the Details & Assumption, should we add: create a setup.cfg file with all of my nosetests options?
