### ISSUE TITLE
read a shopcart by customer_id

### ISSUE THREAD

**Issue by wyf2154** [nyu-devops-squad/shopcarts#9]
**As a** service manager
**I need** to read existing shopcart details  
**So that** we can show details on the page and send them to the next page.  

**Details & Assumptions:** 
* shopcart is already created

**Acceptance Criteria:**

```gherkin
Given an existing shopcart
When a request for reading a shopcart is in
Then details of shopcart are read
```

**Comment by aanchal22** [comment]
Details addded
